# Лабораторная работа №8

## Студент

**ФИО:** Щеголяев Максим Ильич\
**Группа:** НБИбд-02-25\
**№ студенческого:** 1032256490

------------------------------------------------------------------------

## 1. Цель работы

Изучение инструментов поиска файлов, перенаправления ввода-вывода,
фильтрации данных, а также получение практических навыков управления
процессами и анализа использования дискового пространства.

------------------------------------------------------------------------

## 2. Теоретическая часть

### 2.1 Потоки ввода-вывода

В операционной системе существуют три стандартных потока: - stdin (0)
--- ввод - stdout (1) --- вывод - stderr (2) --- ошибки

### 2.2 Перенаправление

-   `>` --- перезапись файла\
-   `>>` --- добавление\
-   `<` --- ввод из файла

Примеры:

    ls > files.txt
    ls >> files.txt

### 2.3 Конвейеры

Позволяют передавать вывод одной команды в другую:

    ls -l | grep conf

### 2.4 Команда find

    find ~ -name "*.txt"

### 2.5 Команда grep

    grep "text" file.txt

### 2.6 Команды df и du

-   df --- показывает диски
-   du --- показывает размер каталогов

### 2.7 Управление процессами

-   ps --- процессы
-   kill --- завершение
-   jobs --- задачи

------------------------------------------------------------------------

## 3. Практическая часть

### 3.1 Запись файлов

    ls /etc > file.txt
    ls ~ >> file.txt

### 3.2 Фильтрация .conf

    grep ".conf" file.txt > conf.txt

### 3.3 Поиск файлов

    find ~ -name "c*"

### 3.4 Постраничный вывод

    ls /etc | more

### 3.5 Фоновый процесс

    find ~ -name "log*" > logfile &

### 3.6 Управление процессами

    ps aux | grep gedit
    kill PID

### 3.7 Проверка диска

    df -h
    du -a ~

------------------------------------------------------------------------

## 4. Ответы на контрольные вопросы

1.  stdin, stdout, stderr\

2.  --- перезапись, \>\> --- добавление

3.  Конвейер --- передача данных между командами\

4.  Процесс --- выполняемая программа\

5.  PID --- идентификатор процесса\

6.  jobs --- управление задачами\

7.  top/htop --- мониторинг системы\

8.  find --- поиск файлов\

9.  Да, через grep\

10. df\

11. du\

12. kill

------------------------------------------------------------------------

## 5. Вывод

В ходе выполнения работы были изучены основные команды Linux для работы
с файлами, процессами и потоками данных. Получены практические навыки
работы в терминале.

------------------------------------------------------------------------

## 6. Заключение

Данная лабораторная работа является важной частью освоения операционных
систем, так как позволяет понять базовые принципы взаимодействия с
системой.
